###### PARAMETERS #######
SEED : 4436
Q : 1
n_backtest_days : 30
first_prediction_day : 704 # The day on which you make your first prediction
target_feature : 0
SVD_niter : 7 
SVD_random_state : 435 
quantile : 1 #The top quantile stocks with the strongest predictions  
embedding_method : "Pearson Correlation" #One of 'Pearson Correlation' (Default), 'Precision Matrix', 'Spearman Correlation', 'Kendall Correlation', 'Covariance Matrix'
lookback_window : 704
num_lags : 1
num_factors : 1
