###### PARAMETERS #######
SEED : 4436
Q : 1
n_backtest_days : 240
first_prediction_day : 480 # December 1999
target_feature : 0
SVD_niter : 7 
SVD_random_state : 435 
quantile : 1 #The top quantile stocks with the strongest predictions  
embedding_method : 'Precision Matrix' #One of 'Pearson Correlation' (Default), 'Precision Matrix', 'Spearman Correlation', 'Kendall Correlation', 'Covariance Matrix"
lookback_window : 480